/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux i108588318 5.11.0-37-generic x86_64"
#define LGL_COMPILED "Thu 10 Feb 2022 06:26:29 PM MSK"
#define LGL_RELEASED "Tue Apr 29 19:18:48 CEST 2014"
#define LGL_VERSION "ayv"
#define LGL_ID "86bf266b9332599f1b876e28a02fe8427aeaa2db"
