all:
	##################################################
	###                 PaInleSS                   ###
	##################################################
	+ $(MAKE) libpainless-lib-static.a -C painless-src
	mv painless-src/libpainless-lib-static.a libpainless-lib-static.a

clean:
	+ $(MAKE) clean -C painless-src
