/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux dzhiblavi-UPC 5.13.0-28-generic x86_64"
#define LGL_COMPILED "Thu 10 Feb 2022 08:44:23 PM MSK"
#define LGL_RELEASED "Tue Apr 29 19:18:48 CEST 2014"
#define LGL_VERSION "ayv"
#define LGL_ID "86bf266b9332599f1b876e28a02fe8427aeaa2db"
