cc_library(
    name = "domain",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cpp"]),
    deps = [
        "//core/util:util",
        "//core/sat/minisat:minisat",
    ],
    visibility = ["//visibility:public"],
)